name: Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          rsync -avz -e "ssh -i keyfile -o StrictHostKeyChecking=no" --rsync-path="sudo rsync" --delete dist/ carlosamerico@104.248.119.181:/var/www/admin.caducoder.dev.br/
          rm keyfile
